version: '2'
services:
  main-service-1:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 10
    container_name: main-service
    ports:
    - 8080:8080
    - 9000:9000
    - 8081:8081
    environment:
      - HOST=0.0.0.0
      - PORT=8080
