FROM selenium/standalone-chrome:latest

USER root
WORKDIR /home/app
COPY requirements.txt  requirements.txt

RUN apt-get update && apt install -y python3 && apt install -y python3-dev && apt install -y python3-pip

USER seluser
RUN python3 -m pip install --upgrade pip
RUN pip3 install -r requirements.txt

COPY alembic alembic
COPY dto dto
COPY models models
COPY settings settings
COPY src src
COPY alembic.ini alembic.ini
COPY main.py main.py
COPY pr.py pr.py
COPY run_play.py run_play.py

RUN nohup /opt/bin/entry_point.sh &

CMD python3 main.py
